# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t50FSwfkbNGHM6ml7hTepGqcSkC6FeLb
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install flask-ngrok

!pip install gspread

from flask import Flask,render_template,url_for,request
import requests
import pandas as pd
import threading
from flask_ngrok import run_with_ngrok
import matplotlib as ml
import matplotlib.pyplot as plt
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <h1><strong>PART 1 : </strong></h1>

data = pd.read_csv('/content/drive/My Drive/data - data.csv')
data.head(10)

data.info()

data.replace("\\N","Not Mentioned",inplace=True)
data.head(10)

data['request_received'] = pd.to_datetime(data['request_received'])
data['response_delivered'] = pd.to_datetime(data['response_delivered'])
data.info()

data.to_csv('data_new.csv')

"""## Visualization :"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <div class='tableauPlaceholder' id='viz1593905277312' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ED&#47;EDA-ScreeningTest&#47;EDAonprovideddatasetexcludingrecommendation_id&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='EDA-ScreeningTest&#47;EDAonprovideddatasetexcludingrecommendation_id' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;ED&#47;EDA-ScreeningTest&#47;EDAonprovideddatasetexcludingrecommendation_id&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-GB' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1593905277312');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1016px';vizElement.style.height='991px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <h1><strong>PART 2 : </strong></h1>

"""## The frontend files are in my Drive : 

A. templates folder : https://drive.google.com/drive/folders/1-3cAhuiI-QopPPUKDzXOKo3N39DNK7T4?usp=sharing
1. index.html - https://drive.google.com/file/d/1-E8tp8-p0iaVM8PQVIulNvESjAJHW6DO/view?usp=sharing
2. predict.html - https://drive.google.com/file/d/1-MJeN3jN0W1GDTzF5HwSn3oiSsn9Mivo/view?usp=sharing

B. CSV file(dataset) : https://drive.google.com/file/d/13_8fCDuFa4P0TQE213LMfomSdM1MvrHQ/view?usp=sharing


## App screenshots :

#### Home page -

![SS 1](https://user-images.githubusercontent.com/49288068/86520949-d274cb80-be67-11ea-9002-c6a822c5c4b7.png)

________________________________________________________________________________

#### Options -

![SS 2](https://user-images.githubusercontent.com/49288068/86520952-e8828c00-be67-11ea-9af7-73c6ff713203.png)

________________________________________________________________________________

#### For categories with number of images < 550 -

![SS 3](https://user-images.githubusercontent.com/49288068/86520960-094ae180-be68-11ea-9fff-8aac8fb0d252.png)

________________________________________________________________________________

#### For categories with number of images > 550 -

![SS 4](https://user-images.githubusercontent.com/49288068/86520972-339c9f00-be68-11ea-8bde-581d842e56f4.png)
"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <h1><strong>THE BACKEND CODE : </strong></h1>

data = pd.read_csv('/content/drive/My Drive/dress - dress.csv')       # Code written after mounting my Drive.
data['category'].replace('polka dot','polka_dot',inplace=True)
dress_category = list(set(data.category.values))

app = Flask(__name__,template_folder='drive/My Drive/templates')      # Code written after mounting my Drive.
run_with_ngrok(app)

@app.route("/")
def home():
  return render_template('index.html',dress_category=dress_category)

@app.route('/predict',methods=['POST'])
def predict():
  category = request.form.get('item')
  links = sorted(list(data[data.category == category].image_url.values))
  return render_template('predict.html',dress_category = dress_category,links = links)

app.run()

"""## Execution Screenshot

![Execution logs](https://user-images.githubusercontent.com/49288068/86525998-e3473080-beab-11ea-91a7-916bc49f3929.png)
"""

